[project]
name = "3-cicd-automation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ibm-cloud-sdk-core>=3.24.2",
    "ibm-watsonx-ai>=1.4.7",
]
