[project]
name = "0-prerequisites"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ibm-watsonx-ai>=1.4.6",
    "python-dotenv>=1.2.1",
    "streamlit>=1.51.0",
    "pydantic>=2.0.0",
    "requests>=2.31.0",
]
