[project]
name = "3-orchestrate"
version = "0.1.0"
description = "Setting up watsonx Orchestrate via ADK"
readme = "README.md"
requires-python = "=3.11"
dependencies = [
    "ibm-watsonx-orchestrate>=1.15.0",
]
